var profession = {
	fighter:{
		name:"Fighter",
		hitDice:5,
		mana:1,
		strength:2,
		dexterity:1,
		toughness:2,
		willpower: 0,
		mental: 0,
		startingWeapon: "longSword",
		startingArmor:"chainArmor",
		startingWand:"firWand",
		startingSymbol:"woodSymbol",
		startingAccessory:"copperRing"
	},
	healer:{
		name:"Healer",
		hitDice:1,
		mana:5,
		strength:0,
		dexterity:0,
		toughness:1,
		willpower: 3,
		mental: 1,
		startingWeapon: "dagger",
		startingArmor:"paddedArmor",
		startingWand:"mahoganyWand",
		startingSymbol:"steelSymbol",
		startingAccessory:"bronzeRing"
	},
	paladin:{
		name:"Paladin",
		hitDice:3,
		mana:2,
		strength:2,
		dexterity:0,
		toughness:1,
		willpower: 2,
		mental: 0,
		startingWeapon: "cutlass",
		startingArmor:"hideArmor",
		startingWand:"firWand",
		startingSymbol:"bronzeSymbol",
		startingAccessory:"copperRing"
	},
	thief:{
		name:"Thief",
		hitDice:2,
		mana:3,
		strength:1,
		dexterity:3,
		toughness:1,
		willpower: 0,
		mental: 0,
		startingWeapon: "rapier",
		startingArmor:"leatherArmor",
		startingWand:"oakWand",
		startingSymbol:"copper",
		startingAccessory:"bronzeRing"
	},
	wizard:{
		name:"Wizard",
		hitDice:1,
		mana:5,
		strength:0,
		dexterity:0,
		toughness:1,
		willpower: 1,
		mental: 3,
		startingWeapon: "dagger",
		startingArmor:"clothArmor",
		startingWand:"obsidianWand",
		startingSymbol:"copperSymbol",
		startingAccessory:"steelRing"
	}
}